# Minima theme settings
theme: minima

# Site settings
title: My Awesome Site
description: >- # This is a multiline description
  A blog about awesome things with the Minima theme.
author:
  name: Your Name
  email: youremail@example.com

minima:
  skin: classic # You can choose from classic, dark, solarized, and solarized-dark
  social_links:
    twitter: your_twitter_handle
    github: your_github_username
    linkedin: your_linkedin_profile

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - index.md
  - about.md
  - contact.md
